### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by kisyular** [kisyular/MI-449-SS17-740-css-intro-iMnt09#1]
@KatieMFritz Can you take a look at this? It's [hosted here](https://kisyular.github.io/MI-449-SS17-740-css-intro-iMnt09/) and meets the following criteria:

- [x] Your project is built off [this base HTML and CSS](https://gist.github.com/chrisvfritz/279c36ab6e2301e8a35526be028d8a32) (you may modify both pages however you want, e.g. adding classes or more elements)
- [x] The website looks (nearly) identical to [this mockup](https://i.imgur.com/pGemyxp.png) -- colors must be exact, spacing/sizes should be within about `5px` (use the _Page Ruler_ extension to measure exact sizes/spacing; you might need to open the image in a new tab)
- [x] Any CSS selectors or properties may be used, though the project is possible using only what you saw in the lesson
- [x] No spacing HTML (e.g. `<br>`, `&amp;nbsp;`) is added to `index.html`
- [x] Add at least one link (`a` element) to the page and style them to be `purple` normally, but turn `orange` on hover

**Comment by KatieMFritz** [comment]
Hi Rellika,

Looks like you did `git push origin master:gh` instead of `git push origin master:gh-pages` - there's nothing showing up on your hosted site!

Please type `git push origin master:gh-pages` again in your terminal, then makes sure your site is showing up [at the github pages link](https://kisyular.github.io/MI-449-SS17-740-css-intro-iMnt09/), then let me know and I'll review it.

Thanks!

**Comment by kisyular** [comment]
@KatieMFritz , I update the GitHub Pages. Please help me review

**Comment by stuartpearman** [comment]
Hi Rellika, I'm helping Katie out with code reviews today 😎 

This is great, two things I would change though:

1. Add a white background to the `header`
2. Put some additional spacing between the `header` and first `section` tag

Keep up the good work! :+1:

**Comment by kisyular** [comment]
@stuartpearman I made the necessary changes you kindly suggested. 

Thank you

**Comment by KatieMFritz** [comment]
I'm back! Thanks for your help, @stuartpearman .

When I looked at your hosted site, I didn't see those changes. So then I looked at your  CSS, and noticed there's [a space missing at line 49](https://github.com/kisyular/MI-449-SS17-740-css-intro-iMnt09/blob/gh-pages/css/style.css#L49). I'm pretty sure that's getting in the way of the styles being applied. 😖 

This will definitely not be the last time that a single space or other character throws off your entire project! Happens to the best of us. 😄 Atom tools like [linter packages](https://msu.lansing.codes/courses/MI-449-SS17-740/lessons/html-boilerplate-linting-and-code-style/2) and the [`Show Invisibles` setting](https://msu.lansing.codes/courses/MI-449-SS17-740/lessons/html-boilerplate-linting-and-code-style/3) can help you catch typos as you write.

After you fix that, here are some other things to change in this project:

- less space at the *top* of the city `section`s
- more space on the *left* and *bottom* of the city `section`s
- more space between the city name and city description
- less space between Friends List and the tagline
- in the city `section`s, the text, horizontal line, and images should all line up on the left, as if there is an invisible line touching all of them

It looks like I'm more picky than Stuart! You are off to a great start though. Let me know if you get stumped on any of those changes, or you can't see the difference. 🚀

**Comment by kisyular** [comment]
@KatieMFritz, I made the changes you requested

**Comment by KatieMFritz** [comment]
Hi Rellikson, 

Good news: you fixed those things! 🎉 

Bad news: there are some different things not matching now! 😬 

- There's the right amount of vertical space between the two city `section`s, but the space between them is white now instead of tan. 
- There are 7 photos per row now instead of 6. This is because there isn't enough space between photos (horizontally) and on the left and right sides of the `section`s. 
- There's too much space between the city names and the lines below them

Again, let me know if there's anything you're not seeing or can't figure out, and comment here when it's fixed! 🎈

**Comment by kisyular** [comment]
@KatieMFritz, I made the changes you requested. Kindly take a look and let me know

**Comment by KatieMFritz** [comment]
Okay, that's close enough. 😁 

I know this project is one of the more frustrating ones - it's really hard to match all those measurements! Unfortunately, as you maybe have already experienced with your other development work, the real world can be like this. Clients can be picky, or even change their requirements partway through the project. This lesson is good practice for graciously handling multiple rounds of feedback. You did great. 🎉 

:shipit: !

By the way, your commit messages are very descriptive! That's a fantastic habit.
